# Generated by Django 4.2.3 on 2023-07-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='beers.brewery'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='hops',
            field=models.ManyToManyField(blank=True, related_name='beers', to='beers.hop'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='beers.beerstyle'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='volume_ml',
            field=models.PositiveIntegerField(help_text='Volume of the beer in milliliters [mL]'),
        ),
    ]
