# Generated by Django 3.2.5 on 2021-07-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='hops',
            field=models.ManyToManyField(blank=True, to='beers.Hop'),
        ),
    ]
