# Generated by Django 3.2.5 on 2021-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_beer_hops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'verbose_name_plural': 'Breweries'},
        ),
        migrations.AddField(
            model_name='brewery',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
