# Generated by Django 4.2.3 on 2023-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_beer_brewery_alter_beer_hops_alter_beer_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beers'),
        ),
    ]
