# Generated by Django 3.2.5 on 2021-07-15 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20210713_1250'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gt', Decimal('0'))), name='percentage_positive'),
        ),
    ]
