# Generated by Django 4.2.4 on 2023-08-15 09:42

import beers.models.brewery
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_alter_beer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'verbose_name': 'Brewery', 'verbose_name_plural': 'Breweries'},
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='established',
        ),
        migrations.AddField(
            model_name='brewery',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=beers.models.brewery.get_brewery_image_path),
        ),
        migrations.AddField(
            model_name='brewery',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[beers.models.brewery.year_validator]),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
