# Generated by Django 3.2.5 on 2021-07-15 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20210715_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
