# Generated by Django 3.2.5 on 2021-07-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_alter_beer_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['id']},
        ),
    ]
