# Generated by Django 4.2.4 on 2023-08-15 13:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_alter_hop_options_alter_hop_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='extract',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Concentration of dissolved solids (mainly sugars) in a brewery wort. [°BLG]', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
