# Generated by Django 3.2.5 on 2021-12-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_alter_beer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='IBU',
            field=models.PositiveIntegerField(blank=True, help_text='Bitterness measured in International Bitterness Units scale', null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='extract',
            field=models.PositiveIntegerField(blank=True, help_text='Concentration of dissolved solids (mainly sugars) in a brewery wort. [°BLG]', null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='hop_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Grams of hops per liter [g/L]', null=True),
        ),
    ]
