# Generated by Django 4.1.1 on 2022-09-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_auto_20211223_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={},
        ),
    ]
