# Generated by Django 5.1.2 on 2024-11-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_alter_beer_extract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='volume_ml',
        ),
    ]
