# Generated by Django 4.2.4 on 2024-02-24 18:49

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0008_alter_beer_extract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging', models.CharField(choices=[('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('KEG', 'Keg'), ('DRAUGHT', 'Draught')], max_length=7)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the beer in Polish Zloty [PLN]', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume of the beer in milliliters [mL]', validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image', models.ImageField(blank=True, help_text='Image of the receipt, menu or the beer itself', null=True, upload_to='purchases/')),
                ('purchased_at', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='beers.beer')),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beer Purchase',
                'verbose_name_plural': 'Beer Purchases',
            },
        ),
    ]
