# fly.toml file generated for beerdegu on 2023-07-04T14:30:39+02:00
# https://fly.io/docs/reference/configuration/

app = "beerdegu"
kill_signal = "SIGINT"
kill_timeout = 5
[processes]
  app = "daphne -b 0.0.0.0 -p 8000 core.asgi:application -v2"
  worker = "python manage.py qcluster"

[build]
  dockerfile = "Dockerfile.fly"
  build-target = "runtime"

[deploy]
  release_command = "python manage.py migrate"

[env]
  DJANGO_SETTINGS_MODULE = "core.settings.prod"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  internal_port = 8000
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[statics]]
    guest_path = "/app/staticfiles"
    url_prefix = "/static"
