# Generated by Django 4.2.4 on 2023-08-12 21:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beers', '0004_alter_beer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_through', to='beers.beer')),
            ],
            options={
                'verbose_name_plural': 'Beers in Room',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique room name', max_length=8, unique=True)),
                ('password', models.CharField(blank=True, help_text='Password needed to join the room. Leave blank if you want the room to be public.', max_length=20, null=True)),
                ('slots', models.PositiveIntegerField(default=1, help_text='Maximum number of participants in the room (including host)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('state', models.CharField(choices=[('WAITING', 'Waiting'), ('STARTING', 'Starting'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished')], default='WAITING', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beers', models.ManyToManyField(blank=True, help_text='Beers to be reviewed in the room', related_name='rooms', through='rooms.BeerInRoom', to='beers.beer')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_hosted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_through', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users in Room',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users currently present in the room', related_name='rooms_joined', through='rooms.UserInRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beerinroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers_through', to='rooms.room'),
        ),
    ]
