# Generated by Django 3.2.5 on 2021-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210713_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerinroom',
            name='ratings',
            field=models.ManyToManyField(related_name='belongs_to', to='rooms.Rating'),
        ),
    ]
