# Generated by Django 4.2.3 on 2023-07-16 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_beer_brewery_alter_beer_hops_alter_beer_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_alter_beerinroom_beer_alter_beerinroom_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='beer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='beers.beer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
