# Generated by Django 3.2.5 on 2021-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_beerinroom_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerinroom',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='belongs_to', to='rooms.Rating'),
        ),
    ]
