# Generated by Django 4.2.3 on 2023-07-16 11:23

from django.db import migrations


def forward_func(apps, schema_editor):
    BeerInRoom = apps.get_model('rooms', 'BeerInRoom')
    db_alias = schema_editor.connection.alias

    beers_in_rooms = BeerInRoom.objects.using(db_alias).all()

    for beer_in_room in beers_in_rooms:
        ratings = beer_in_room.ratings.using(db_alias).all()
        ratings.using(db_alias).update(room=beer_in_room.room, beer=beer_in_room.beer)


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0004_rating_beer_rating_room_alter_rating_added_by'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
        )
    ]
