# Generated by Django 4.2.3 on 2023-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_beer_brewery_alter_beer_hops_alter_beer_style_and_more'),
        ('rooms', '0005_migrate_beer_room_to_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='beers.beer'),
        ),
    ]
