# Generated by Django 4.2.3 on 2023-07-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_rating_beer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerinroom',
            name='ratings',
        ),
    ]
