# Generated by Django 3.2.5 on 2021-07-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_rating_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['id']},
        ),
    ]
