# Generated by Django 4.2.4 on 2023-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_beerinroom_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
