# Generated by Django 4.2.3 on 2023-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beerinroom',
            options={'ordering': ('order',), 'verbose_name_plural': 'Beers in Room'},
        ),
        migrations.AddField(
            model_name='beerinroom',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
