# Generated by Django 4.2.3 on 2023-07-12 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0011_beerinroom_created_at_beerinroom_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_hosted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rooms_joined', through='rooms.UserInRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_through', to=settings.AUTH_USER_MODEL),
        ),
    ]
