# Generated by Django 4.2.4 on 2024-04-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='beer_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='purchases.beerpurchase'),
        ),
    ]
